version: "3.3"
services:
  java_service:
    build: .
    ports:
      - "8080:8080"
    container_name: student-management
    networks:
      - net1
  
networks:
  net1:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 15.15.0.0/16
